Algoritmo "ex002"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/08/2024
Var
milhas, metros : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval ("digite o valor de milhas percorridas pelo atleta")
 leia (milhas, metros)
 metros <- milhas*1609
 //cada milha representa 1.609 metros
escreval ("a quantidade em metros é", metros)

Fimalgoritmo