Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/09/2024
Var

soma,numero : real
tabuada,i,resultado : inteiro
Inicio
Escreval("Qual o número?")
Leia(tabuada)
Para tabuada de 1 até 10 faça
   Para i de 1 até 10 faça
        resultado <- i * tabuada
        Escreva(tabuada, " x", i)
        Escreval(" =", resultado)
   Fimpara
Fimpara
Fimalgoritmo