Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/09/2024
Var
// Seção de Declarações das variáveis 
numero : real
i : inteiro
maior, menor : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Para i de 1 até 10 Faça
     Escreval("Informe os números")
     Leia(numero)

     
     
Fimpara


Fimalgoritmo